spring:
  application:
    name: "citizen-server"
  profiles:
    active: origin
    default: Mok

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/CityManagment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      bootstrap-servers: localhost:29092

server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true