spring:

  profiles:
    active: origin
    default: Mok

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/CityManagment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
