spring:
  profiles:
    active: origin
    default: Mok
  datasource:
    url: jdbc:postgresql://localhost:5432/CityManagment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
